# Generated by Django 2.2.5 on 2019-09-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0002_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='events',
            field=models.ManyToManyField(to='eventFinderApp.Event'),
        ),
    ]
