# Generated by Django 2.2.5 on 2019-09-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0003_category_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Attendees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_attendees_id', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='events',
        ),
        migrations.CreateModel(
            name='Event_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category_id', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=50)),
                ('category_id', models.CharField(max_length=50)),
                ('category', models.ManyToManyField(to='eventFinderApp.Category')),
                ('events', models.ManyToManyField(to='eventFinderApp.Event')),
            ],
        ),
    ]
