# Generated by Django 2.2.5 on 2019-09-21 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0004_auto_20190904_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_Attendees',
        ),
        migrations.DeleteModel(
            name='Event_Categories',
        ),
    ]
