# Generated by Django 2.2.5 on 2019-09-21 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0005_auto_20190921_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
